[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "829e30673c3d45b1fbe12260ccd98b28510cb1c2"
os = "freebsd"

    [[CImPlot.download]]
    sha256 = "3340b25270454a107a086e626019243aa8d554b50e2abd2295e6d772446bcde1"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.x86_64-unknown-freebsd11.1.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "4ef46c0087b3e0c2250c251b99ee7e0df94ff9a4"
os = "windows"

    [[CImPlot.download]]
    sha256 = "34c5a90080027355bb4754fa68ede63a86eecd82e59a0917698d0725cf86480f"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.x86_64-w64-mingw32.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "d9096681d3c8d0eddbcde57ea1798b264beb0491"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "ff0053a40e3558b59f2033bc9d9d91aae9e24b2796eff7137ffbea58aa7d32d7"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.x86_64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "7ac2863aeb98874445aeeeb1436b8829c754e157"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "750cbdcc050667651b73d97846356e2d2f4918a44d70a29a01aa26278fd45930"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.armv7l-linux-musleabihf.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "66cb8c19720ae634e974e2e331b1901a87920f77"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "f235aea949fa9b1bd348b21c7d0a91cd890e59d87ded0a74e880513155f98535"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.i686-linux-gnu.tar.gz"
[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "84fccf2949ef40c31ea9a58c64f794ef014c9d0a"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "a277e802b54ff851e8fd40cdf9268ee8423be31ba1f1a6ab7a5df10310044081"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.aarch64-linux-musl.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "e72a1507eb6a24eb32dffde445b462934a06b0b9"
os = "windows"

    [[CImPlot.download]]
    sha256 = "04e38b42dd7d30c42c8f63e0db52c4a5951dca199027225227886715fdafc126"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.i686-w64-mingw32.tar.gz"
[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "e17fea3168114f990d1fddaf1d2b49f1b1cf4a9a"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "73bc80ab49237e5f1a4e078a18e0941feea098c5ccad4584b71de6d9837395a1"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.aarch64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "e39c6d9a4820a2ae0f713577b6827c663fba494c"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "c01e57f7d0c97789b802ef5a79d09495522c6489c9c3d7e808ee9f0c5b9f188e"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.i686-linux-musl.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "7b433a3909b5844c7db22de736213fef1ef472f0"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "a8f130a986242118056f8d304de9270da225731087ab99ec04d27207a4edc939"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.x86_64-linux-musl.tar.gz"
[[CImPlot]]
arch = "powerpc64le"
git-tree-sha1 = "e6eacf66e8b7815c8eb3248a9b9dd8d1c18d943f"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "3e4ef679f43bec500925b9df2bf90475bc9ccfc021d4e1af11f72f93f9312de1"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.powerpc64le-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "0c9c25147b1a8ca22b7fceb0fb6aa90235feca88"
os = "macos"

    [[CImPlot.download]]
    sha256 = "9f8d231a87bab3202c9fa8d714dc367f42befc4169a632070c7412ab02a42577"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "ec5d8a6d668099bcde0aafa8003f3a9678aa872e"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "cee261d4dc05778c65d2c111d4ab8510374f8519daf53ad42ff69fb8b24b6ca2"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.0.1+0/CImPlot.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
