[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "a2e412fb669264d41fb71daf43f8461a64d7d052"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "279554e62122c7991d3d202ff08a229eafba6a42ed81175bbaa41682a9f5c5b2"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.aarch64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "03f182e6b9e79c6383e0bbffb487ab7c2ff6c0e8"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "4f85253b16bcb40b5e3086c77c8930b21fc1cd566521f2b5ed4057df2884527b"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.aarch64-linux-musl.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "cfbb4cf05a8cf28f4a7341ec62345db659c18ed9"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "11c8a2ea50bb1a28d69a853477dcf0f29991c5dd831ca880fd05faad7fdf3f9f"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.armv7l-linux-gnueabihf.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "0c0e68c2458491c5973bf785f0704700647e8660"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "120f8e31f51dc6d2ef5f3ad54a9cffa5a06eb3f671f413ab75f499c37b94489d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.armv7l-linux-musleabihf.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "b8614cc1731fd059ae314cf18385df526aac41a6"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "f55a80940f5fca36e104e3aa8eaa3da3d72e589d45a64d95e6573ad571ba9126"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.i686-linux-gnu.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "e9d74c7b5c24bad4cb17535a1ab27a2eb526ea38"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "13dd5b3ec6c729aea839ec0fd5d08c61dd19719d3810631b257f6badb8a04207"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.i686-linux-musl.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "eb17d53ae4e3a283a4243f14655ba389d436ae55"
os = "windows"

    [[CImPlot.download]]
    sha256 = "69b156527e1877ec509ccd2cd6ea56f502c1ffef7d722999067d086887a478f3"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.i686-w64-mingw32.tar.gz"
[[CImPlot]]
arch = "powerpc64le"
git-tree-sha1 = "9fed6db6d1e8bedccc801e3d6a64f4b0f88364f6"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "591a03a728d1370a091f04bf14523f19e1417e5ee3fed5cff6868c84822729ae"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.powerpc64le-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "b8a54fe4c92699603e415eb665dc8e20c804197c"
os = "macos"

    [[CImPlot.download]]
    sha256 = "c10768c50a96474da7274edc686c66b6559862fa2d1b30bb65ade006b0066eb5"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.x86_64-apple-darwin14.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "efe6dc806a7a8691c45f48a2b9842b18ef21f446"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "4cf9811e9788a0a7bde73f99ee13730433b338966d3486d11ad48fd1658e67a5"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.x86_64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "9dccd307f1444298c1dec8aa182747ed5f0e4356"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "8b29e723a99878bb5a0ea3d434e0f2d2416458966243b9f38c5f7b61c369a96e"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.x86_64-linux-musl.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "4cb4deddbff4a703abc5af064a32bd2fef359e2a"
os = "freebsd"

    [[CImPlot.download]]
    sha256 = "97bb7e3ee8171e9f4043feb6ba6d0fe0e6928cad05578d164479e4edc4ab7b78"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "052b707eb94f38ce0b32b08f44857bb4f4e8da24"
os = "windows"

    [[CImPlot.download]]
    sha256 = "15a10883dd01fc13ab832d83fcfe4b79aac77a16f03bfc6929f35def03cc23e8"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.3.0+0/CImPlot.v0.3.0.x86_64-w64-mingw32.tar.gz"
