[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "9f776711701730a1b37bb07442889fd468115f60"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "47474d0d1b08fa77235ddeb192aad367f146bce4e5f7f06235f9ae5f49a08319"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.aarch64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "5e1e03ad74280bae30ee36cc5c5b3adf0606a2a6"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "4bd1376e080eec42ddd6084a2d54b86d3f9dfe49256c559fce81360883cf471d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.aarch64-linux-musl.tar.gz"
[[CImPlot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "193416cfeb51f1df554689cddebe95eea01fc10d"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "19e166e12525cd94c30f876a24dbf4229df85ae54d881991154cf51583619c20"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.armv7l-linux-gnueabihf.tar.gz"
[[CImPlot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bfcead5eb91c397b5680a898de8093dd4538602c"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "fda0f861f705b0d42ac70c27a8c52a4c91567795d5d30976480efadc3284a3cf"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.armv7l-linux-musleabihf.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "80dd629d5de29d6a2a6493e7d3e88e405bf95e70"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "6d196b6b8d30d562bce0faf3025294e3707da71155d2493396e5b1d67fde6003"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.i686-linux-gnu.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "fe9f74a0f5eed96245cbea778f69c5a0c9c51388"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "3509f03bbb67eeceee37058369b89b0484cda087956479e7201f5156a7ecbfc5"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.i686-linux-musl.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "b846f6caface7075e2e08eb1b44885af5f4f8881"
os = "windows"

    [[CImPlot.download]]
    sha256 = "2b00d8f16f4d48bf5c3d017b374a96c4e3730d5f8b479acb757410a44eb98420"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.i686-w64-mingw32.tar.gz"
[[CImPlot]]
arch = "powerpc64le"
git-tree-sha1 = "7d17d9ec20eb3fc1b0e433fec79430b5b6b27002"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "51599ca5c7f91e41abde08a68ac40cf96cb9961cf5893331a1ec9ccc801590ae"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.powerpc64le-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "362fe24ad6c5ca45dfbfcdb6e6561f4265a7dae8"
os = "macos"

    [[CImPlot.download]]
    sha256 = "47d40cd5bc90903d6117b46eddb9aa70d424309c5f895f7e3bb3b69d5d89d39d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.x86_64-apple-darwin.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "5b2b61e1b0721d0f69fa855d20f464a98f4df73f"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "86732c31b5f008266c95ed738aa82fe943e928e8e5409be7df16a4278b261b5d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.x86_64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "052bba9e4b303b96e9fe3627bb4f4c1725db4e09"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "0d651bd8d22719eb01a1ae83cf7bcc8e0bae48a225cf559e717371f17c89276c"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.x86_64-linux-musl.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "99ce45bae111c9020e19603cb6ef125854a94799"
os = "freebsd"

    [[CImPlot.download]]
    sha256 = "a4aed27968650b7c0e9ba0ab7095c93d0021e3616131fd6b10f7c2c534dc241e"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.x86_64-unknown-freebsd.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "bc6d4eab4f69b524f9d68ed421348827a9def601"
os = "windows"

    [[CImPlot.download]]
    sha256 = "5120d1163448ca1e88ec778620016b954030d6fe3fc77bd0181e07a748d4223c"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.8.0+0/CImPlot.v0.8.0.x86_64-w64-mingw32.tar.gz"
