[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "e13c48f0aff64182cb70e27181f550f5429e09d8"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "87c8a506bda00c1bb2a5eaf6e22a271ee30fa380225996b3949dca4fe4e052b5"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.aarch64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "aarch64"
git-tree-sha1 = "e45f52a95cc8a20073b0d7ba703e8603a85f8006"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "695153c3ae7ca8420d96124fee2aebb38b17e0200f9e18a99c2df7e9bda535ce"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.aarch64-linux-musl.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "3f23d62f286922b237f237d9bd38e5849e52c451"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "f6d95ec2eb41299f891fc9f49b73ae17de2e301cb3a0d0a19d3179b6befd46bc"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.armv7l-linux-gnueabihf.tar.gz"
[[CImPlot]]
arch = "armv7l"
git-tree-sha1 = "453f2b931226a23f5c59c30d075a12c34fdaf347"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "64e6d714efcb4fd8c60fadb0970a3aca96d04e1cebf879efd431fafb75541a96"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.armv7l-linux-musleabihf.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "a66ecdaebc7ca9921ef7734135db989347528eb9"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "5db71fc54b5aff56372fdb39de9d9dae0738a1f526704eaa21f68cf58acf167d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.i686-linux-gnu.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "72c0bb9a50c66c51730785343dbf3d3d3efe6ac8"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "c6dc4f14b2e0e0c1abb483de5b0f7adce8731a3d9b93c199ad74ebe5c2254147"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.i686-linux-musl.tar.gz"
[[CImPlot]]
arch = "i686"
git-tree-sha1 = "a83acc256f8c736e5814cd78d2da28d06decc0fd"
os = "windows"

    [[CImPlot.download]]
    sha256 = "17e50c5f6a65b5b9e1e77b785a42549f2e6fb709d3d69a7f0ba2600c8683792f"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.i686-w64-mingw32.tar.gz"
[[CImPlot]]
arch = "powerpc64le"
git-tree-sha1 = "1de3dec2145dcaac5e2eaa47279889b196aa9462"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "d28ed09392fde75df415a1f172602ae2e894aa932a8b7ae6781c7726c097bf3c"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.powerpc64le-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "341c1eec83b8bfac501989ac1980d960336c9084"
os = "macos"

    [[CImPlot.download]]
    sha256 = "69242378654931e0584d76e5c9a026512bb2f87387c9ea25dca808976517c220"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.x86_64-apple-darwin14.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "0cc6a080633fafa03677619f4e0789ff30bba3e8"
libc = "glibc"
os = "linux"

    [[CImPlot.download]]
    sha256 = "f2136f1f333ec0836b1927efb71c1842d991b4986c85619d2e9304bb0d6cb209"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.x86_64-linux-gnu.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "2a2501261134500340a4ce9b3ca9b63b9213801c"
libc = "musl"
os = "linux"

    [[CImPlot.download]]
    sha256 = "650f21f5a61366c9865aa81aefa5d67e0d38fe9312c387a33575e71258c6609d"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.x86_64-linux-musl.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "515a18e1be68f1f69ca1439fd4f61de1fa461ace"
os = "freebsd"

    [[CImPlot.download]]
    sha256 = "b4c12140e3763cc477603c2af90b9f1c269524d0693ccdaef67833d9a316eab9"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.x86_64-unknown-freebsd11.1.tar.gz"
[[CImPlot]]
arch = "x86_64"
git-tree-sha1 = "be408af24fe20df73093188050a28e74c19c5969"
os = "windows"

    [[CImPlot.download]]
    sha256 = "20c7d7a58479c4f55dc93cf7ee46737235cb2a3f463cdd254639da7198986721"
    url = "https://github.com/JuliaBinaryWrappers/CImPlot_jll.jl/releases/download/CImPlot-v0.4.0+0/CImPlot.v0.4.0.x86_64-w64-mingw32.tar.gz"
